services:
  - type: web
    name: smartstudy-api-saikumarreddyappidi
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://saikumarreddyappidi.github.io,https://smartstudy-frontend-saikumarreddyappidi.onrender.com

  - type: static
    name: smartstudy-frontend-saikumarreddyappidi
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://smartstudy-api-saikumarreddyappidi.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
