/**
 * Feature 5 – Export Study Report as PDF
 * Uses jsPDF + jspdf-autotable injected via CDN in index.html
 */
import { LS_QUIZ_RESULTS, LS_POMODORO_SESSIONS } from '../config';

function getJsPDF() {
  const jspdf = window.jspdf;
  if (!jspdf) throw new Error('jsPDF library not loaded. Check CDN scripts in index.html.');
  return jspdf.jsPDF;
}

function headerColor() { return [45, 106, 79]; }   // #2d6a4f

function addPageHeader(doc, title, pageW) {
  doc.setFillColor(...headerColor());
  doc.rect(0, 0, pageW, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text('📚 SmartStudy', 16, 20);
  doc.setFontSize(12);
  doc.setFont(undefined, 'normal');
  doc.text(title, pageW - 16, 20, { align: 'right' });
  doc.setTextColor(31, 41, 55);
}

function addPageFooter(doc, pageNum, pageW, pageH) {
  doc.setFontSize(9);
  doc.setTextColor(156, 163, 175);
  doc.text(`Generated by SmartStudy · Page ${pageNum}`, pageW / 2, pageH - 8, { align: 'center' });
}

export function exportReport(user, analyticsData, quizResultsOverride) {
  const JsPDF = getJsPDF();
  const doc = new JsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const name = user?.name || 'Student';
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const quizResults = quizResultsOverride || JSON.parse(localStorage.getItem(LS_QUIZ_RESULTS) || '[]');
  const pomodoroSessions = JSON.parse(localStorage.getItem(LS_POMODORO_SESSIONS) || '[]');

  // ──────────────────────────────────────
  // PAGE 1 — Cover
  // ──────────────────────────────────────
  doc.setFillColor(...headerColor());
  doc.rect(0, 0, pageW, pageH, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(40);
  doc.setFont(undefined, 'bold');
  doc.text('📚', pageW / 2, 80, { align: 'center' });
  doc.setFontSize(32);
  doc.text('SmartStudy', pageW / 2, 100, { align: 'center' });
  doc.setFontSize(16);
  doc.setFont(undefined, 'normal');
  doc.text('Weekly Study Report', pageW / 2, 118, { align: 'center' });
  doc.setFontSize(14);
  doc.text(name, pageW / 2, 140, { align: 'center' });
  doc.setFontSize(11);
  doc.setTextColor(209, 250, 229);
  doc.text(`Generated on ${today}`, pageW / 2, 155, { align: 'center' });
  addPageFooter(doc, 1, pageW, pageH);

  // ──────────────────────────────────────
  // PAGE 2 — Study Summary
  // ──────────────────────────────────────
  doc.addPage();
  addPageHeader(doc, 'Study Summary', pageW);

  const totalHours = analyticsData?.total_hours || 0;
  const productiveHours = analyticsData?.productive_hours || 0;
  const unproductiveHours = analyticsData?.unproductive_hours || 0;
  const completedPomodoro = pomodoroSessions.filter(s => s.completed);

  doc.setFontSize(13);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(6, 78, 59);
  doc.text('Study Summary', 16, 46);

  const summaryData = [
    ['Metric', 'Value'],
    ['Total Study Hours', `${totalHours} hrs`],
    ['Productive Hours', `${productiveHours} hrs`],
    ['Unproductive Hours', `${unproductiveHours} hrs`],
    ['Productivity Score', `${analyticsData?.productivity_score || 0}/100`],
    ['Completed Pomodoro Sessions', completedPomodoro.length.toString()],
  ];

  doc.autoTable({
    head: [summaryData[0]],
    body: summaryData.slice(1),
    startY: 52,
    theme: 'grid',
    headStyles: { fillColor: headerColor(), textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 11 },
  });

  // Daily breakdown from pomodoro
  if (completedPomodoro.length > 0) {
    const byDate = {};
    completedPomodoro.forEach(s => {
      if (!byDate[s.date]) byDate[s.date] = { sessions: 0, minutes: 0 };
      byDate[s.date].sessions++;
      byDate[s.date].minutes += s.duration_minutes;
    });
    const dailyRows = Object.entries(byDate).slice(-7).map(([date, v]) => [
      date,
      `${(v.minutes / 60).toFixed(1)} hrs`,
      `${v.minutes} min`,
      v.sessions.toString(),
    ]);
    if (dailyRows.length > 0) {
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(6, 78, 59);
      const afterY = (doc.lastAutoTable?.finalY || 100) + 12;
      doc.text('Daily Breakdown (Last 7 Days)', 16, afterY);
      doc.autoTable({
        head: [['Date', 'Hours', 'Focus Time', 'Sessions']],
        body: dailyRows,
        startY: afterY + 6,
        theme: 'striped',
        headStyles: { fillColor: headerColor(), textColor: [255, 255, 255] },
        alternateRowStyles: { fillColor: [240, 253, 244] },
        styles: { fontSize: 10 },
      });
    }
  }

  addPageFooter(doc, 2, pageW, pageH);

  // ──────────────────────────────────────
  // PAGE 3 — Topic Mastery
  // ──────────────────────────────────────
  doc.addPage();
  addPageHeader(doc, 'Topic Mastery', pageW);

  const subjects = user?.subjects ? user.subjects.split(',').map(s => s.trim()).filter(Boolean) : [];
  const topicsInQuiz = [...new Set(quizResults.map(r => r.topic).filter(Boolean))];
  const allTopics = [...new Set([...subjects, ...topicsInQuiz])];

  const topicRows = allTopics.map(topic => {
    const related = quizResults.filter(r => r.topic?.toLowerCase() === topic.toLowerCase());
    const avgAccuracy = related.length
      ? Math.round(related.reduce((s, r) => s + (r.accuracy || 0), 0) / related.length)
      : 0;
    const mastery = Math.min(Math.round(avgAccuracy * 0.5 + Math.min(related.length * 10, 100) * 0.2), 100);
    const status = mastery >= 80 ? 'Strong ✅' : mastery >= 50 ? 'Needs Review ⚠️' : 'Weak ❌';
    const last = related.length ? new Date(related[related.length - 1].timestamp).toLocaleDateString() : 'Never';
    return [topic, `${mastery}%`, status, `${avgAccuracy}%`, last];
  });

  doc.setFontSize(13);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(6, 78, 59);
  doc.text('Topic Mastery', 16, 46);

  doc.autoTable({
    head: [['Topic', 'Mastery', 'Status', 'Quiz Accuracy', 'Last Studied']],
    body: topicRows.length > 0 ? topicRows : [['No topic data available', '', '', '', '']],
    startY: 52,
    theme: 'grid',
    headStyles: { fillColor: headerColor(), textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 10 },
    didParseCell(data) {
      if (data.column.index === 2 && data.row.section === 'body') {
        const v = data.cell.raw;
        if (v?.includes('Strong')) data.cell.styles.textColor = [5, 150, 105];
        else if (v?.includes('Needs')) data.cell.styles.textColor = [217, 119, 6];
        else if (v?.includes('Weak')) data.cell.styles.textColor = [220, 38, 38];
      }
    },
  });
  addPageFooter(doc, 3, pageW, pageH);

  // ──────────────────────────────────────
  // PAGE 4 — Quiz Performance
  // ──────────────────────────────────────
  doc.addPage();
  addPageHeader(doc, 'Quiz Performance', pageW);

  const quizRows = quizResults.slice(-20).map(r => [
    r.topic || 'Unknown',
    `${r.score}/${r.total}`,
    `${r.accuracy}%`,
    r.timestamp ? new Date(r.timestamp).toLocaleDateString() : '',
  ]);

  const avgAccuracy = quizResults.length
    ? Math.round(quizResults.reduce((s, r) => s + (r.accuracy || 0), 0) / quizResults.length)
    : 0;

  doc.setFontSize(13);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(6, 78, 59);
  doc.text(`Quiz Performance  |  Average Accuracy: ${avgAccuracy}%`, 16, 46);

  doc.autoTable({
    head: [['Topic', 'Score', 'Accuracy', 'Date']],
    body: quizRows.length > 0 ? quizRows : [['No quiz data available', '', '', '']],
    startY: 52,
    theme: 'striped',
    headStyles: { fillColor: headerColor(), textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    styles: { fontSize: 10 },
  });

  addPageFooter(doc, 4, pageW, pageH);

  // ──────────────────────────────────────
  // PAGE 5 — AI Recommendations
  // ──────────────────────────────────────
  doc.addPage();
  addPageHeader(doc, 'AI Recommendations', pageW);

  const weakTopics = allTopics.filter(topic => {
    const related = quizResults.filter(r => r.topic?.toLowerCase() === topic.toLowerCase());
    if (!related.length) return false;
    const avg = Math.round(related.reduce((s, r) => s + (r.accuracy || 0), 0) / related.length);
    return avg < 50;
  });

  doc.setFontSize(13);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(6, 78, 59);
  let curY = 46;
  doc.text('Weak Topics', 16, curY);
  curY += 8;
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(220, 38, 38);
  if (weakTopics.length === 0) {
    doc.text('No weak topics — great work! 🎉', 16, curY);
    curY += 8;
  } else {
    weakTopics.forEach(t => {
      doc.text(`• ${t}`, 20, curY);
      curY += 7;
    });
  }

  curY += 6;
  doc.setFontSize(13);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(6, 78, 59);
  doc.text('Study Tips', 16, curY);
  curY += 8;
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(31, 41, 55);
  const tips = [
    'Focus your first study session of the day on your weakest topics.',
    'Use spaced repetition for flashcards to maximise retention.',
    'Take a 5-minute break every 25 minutes to sustain focus.',
  ];
  tips.forEach(tip => {
    doc.text(`• ${tip}`, 20, curY, { maxWidth: pageW - 36 });
    curY += 10;
  });

  const projectedReadiness = analyticsData?.productivity_score || avgAccuracy;
  curY += 4;
  doc.setFontSize(13);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(6, 78, 59);
  doc.text(`Projected Exam Readiness: ${projectedReadiness}%`, 16, curY);

  addPageFooter(doc, 5, pageW, pageH);

  // ── Save ──
  const safeName = name.replace(/[^a-z0-9]/gi, '_');
  const dateStr = new Date().toISOString().split('T')[0];
  doc.save(`SmartStudy_Report_${safeName}_${dateStr}.pdf`);
}
